= OST Demo Mappy Server

OST demo application server is a sample implementation of a backend-server for OST wallet built using OST Wallet SDK.

For more details please visit https://dev.ost.com[dev.ost.com]

== Setup

=== 1. Prerequisites

* RVM : install using https://rvm.io/rvm/install[rvm]
* Ruby : using rvm above install Ruby with version >= 2.5.3
* Mysql : run local instance or use https://aws.amazon.com/rds/[AWS RDS]
* Memcache : run local instance using https://memcached.org/[Memcached] or use https://aws.amazon.com/elasticache/memcached/[AWS ElastiCache for Memcached]
* Key Management Services : use https://aws.amazon.com/kms/[AWS KMS]

=== 2. Create configuration file

Refer to link:env.sh.example[env.sh.example] to create a new configuration file (env.sh).

=== 3. Populate ENV Variables

From the configuration file created above, populate ENV variables for the processes below to access.

[source,bash]
----
source env.sh
----

=== 4. Run Database Migrations

==== a. Drop existing tables and databases if any. CAUTION.

[source,bash]
----
rake db:drop:all RAILS_ENV=$RAILS_ENV
----

==== b. Create all the databases.

[source,bash]
----
rake db:create:all RAILS_ENV=$RAILS_ENV
----

==== c. Run all the migrations.

[source,bash]
----
rake db:migrate RAILS_ENV=$RAILS_ENV
----

=== 5. Start Rails Server

[source,bash]
----
bin/rails server -e $RAILS_ENV -p 4000
----

NOTE: For Staging / Production environments we would recommend using https://www.phusionpassenger.com/library/config/nginx/intro.html[Nginx + Passenger]
